CREATE ROLE IF NOT EXISTS test WITH LOGIN;
CREATE DATABASE IF NOT EXISTS analysis;
GRANT ALL ON DATABASE analysis TO test;
CREATE DATABASE IF NOT EXISTS registry;
GRANT ALL ON DATABASE registry TO test;
CREATE DATABASE IF NOT EXISTS crawler;
GRANT ALL ON DATABASE crawler to test;
