services:

  redis:
    image: redis
    ports:
      - 6379:6379

  crdb:
    image: cockroachdb/cockroach:latest-v23.1
    container_name: crdb
    restart: always
    command: start-single-node --insecure
    volumes:
      - crdb:/cockroach/cockroach-data
      - ./crdb_init/:/docker-entrypoint-initdb.d/:ro
    ports:
      - 26257:26257
      - 9080:8080

  acmq:
    image: apache/activemq-artemis:2.36.0
    container_name: acmq
    restart: always
    environment:
      - ARTEMIS_USER=test
      - ARTEMIS_PASSWORD=test
    ports:
      - 61616:61616
      - 8161:8161

  cralwer:
    image: qa-api.tortuga-security.com/tortuga-website-monitor/crawler:2.0.0
    container_name: crawler
    restart: always
    volumes:
      - ./crawler/:/crawler/
    ports:
      - 8081:8080

  simple-analysis:
    image: qa-api.tortuga-security.com/tortuga-website-monitor/simple-analysis:1.0.0
    container_name: simple-analysis
    restart: always
    volumes:
      - ./crawler/:/crawler/
    ports:
      - 8082:8080

  regsitry:
    image: qa-api.tortuga-security.com/tortuga-website-monitor/registry:0.0.1
    container_name: registry
    restart: always
    environment:
      PROFILE: local
    ports:
      - 8083:8080

volumes:
  crdb:
